### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by jr-k** [goblin/mode2_formatter#1]
Hi dude !

Thanks for this repository, I'm ask myself how do you use your output to lirc config file ? I have some a-z letters ok, then what ? how to convert this to lirc file with corresponding values (headers, gap, button, etc.)

**Comment by goblin** [comment]
Hi,

I've expanded the "Examples" section of the README in https://github.com/goblin/mode2_formatter/commit/c441595ab66e22228035ae346cfe0c2b94d0bb21.

Hope this helps.
